### ISSUE TITLE
select box style issue in Firefox 58

### ISSUE THREAD

**Issue by yaodingyd** [joerez/Woah.css#4]
1.The select box text is cutoff
<img width="437" alt="screen shot 2018-03-07 at 13 58 33" src="https://user-images.githubusercontent.com/11392695/37112175-baabd8d2-220f-11e8-980d-7aa44f31ba49.png">

2. Select optgroup text has the same color as background color
<img width="523" alt="screen shot 2018-03-07 at 13 58 39" src="https://user-images.githubusercontent.com/11392695/37112176-bab8fce2-220f-11e8-8f7f-4016dfb77b5e.png">

**Comment by joerez** [comment]
The text color and background should be fixed now. As far as text being cut off I can only assume it's the font-size that is at fault. 

If you create a pull request with a fix for this I will gladly accept it! Thanks!

**Comment by joerez** [comment]
This has been fixed!
